# Generated by Django 3.1 on 2020-10-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jltct',
            options={},
        ),
        migrations.RemoveField(
            model_name='jltct',
            name='section',
        ),
        migrations.RemoveField(
            model_name='jltct',
            name='tag',
        ),
    ]
