# Generated by Django 3.0.8 on 2020-08-01 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0002_auto_20200801_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='login_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
