# Generated by Django 3.1 on 2020-10-30 12:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0002_auto_20201029_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jltct',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
