# Generated by Django 3.1 on 2020-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0002_auto_20201028_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jltct',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='sensei_app.Jltcttag'),
        ),
    ]
