# Generated by Django 3.1 on 2020-10-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0002_auto_20201028_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jltct',
            options={'ordering': ['section', 'number']},
        ),
        migrations.AddField(
            model_name='jltct',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_name', to='sensei_app.jltctsection'),
        ),
        migrations.AddField(
            model_name='jltct',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='sensei_app.jltcttag'),
        ),
    ]
