# Generated by Django 3.0.8 on 2020-08-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
