# Generated by Django 3.1 on 2020-10-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0003_auto_20201030_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='jltct',
            name='related_note',
            field=models.ManyToManyField(blank=True, null=True, related_name='_jltct_related_note_+', to='sensei_app.jltct'),
        ),
    ]
