# Generated by Django 3.0.8 on 2020-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0003_auto_20200729_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
