# Generated by Django 3.0.8 on 2020-07-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0004_question_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='author',
        ),
    ]
