# Generated by Django 3.1 on 2020-10-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0004_auto_20201017_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='JLTCTSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('section_slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JLTCTTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('tag_slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.IntegerField(choices=[(1, 'Choice1'), (2, 'Choice2'), (3, 'Choice3'), (4, 'Choice4'), (5, 'Choice5')], null=True),
        ),
        migrations.CreateModel(
            name='JLTCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='JLTCT_thumbnail')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_name', to='sensei_app.jltctsection')),
                ('tag', models.ManyToManyField(blank=True, null=True, related_name='tags', to='sensei_app.JLTCTTag')),
            ],
        ),
    ]
