# Generated by Django 3.1 on 2020-10-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0005_jltct_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jltct',
            name='public',
        ),
        migrations.CreateModel(
            name='jltctreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensei_app.jltct')),
            ],
        ),
    ]
