# Generated by Django 3.0.8 on 2020-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0005_auto_20200802_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='ニックネーム'),
        ),
    ]
