# Generated by Django 3.1 on 2020-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0006_auto_20201031_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jltct',
            name='reference',
        ),
        migrations.AddField(
            model_name='jltct',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
