# Generated by Django 3.1 on 2020-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0006_jltct_title_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jltct',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='jltct',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jltct',
            name='title_slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jltcttag',
            name='tag_slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
