# Generated by Django 3.1 on 2020-10-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0007_auto_20201031_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jltctreference',
            old_name='reference',
            new_name='name',
        ),
        migrations.AddField(
            model_name='jltctreference',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
