# Generated by Django 3.1 on 2020-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0008_auto_20201031_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmltag', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.TextField(blank=True, null=True)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
