# Generated by Django 3.1 on 2020-11-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0009_markdownexp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarkdownExp',
            new_name='MarkdownExpModel',
        ),
    ]
