# Generated by Django 3.0.8 on 2020-07-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0010_auto_20200730_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
