# Generated by Django 3.1 on 2020-11-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0011_registerperk'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='addition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
