# Generated by Django 3.1 on 2020-11-16 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0012_question_addition'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.TextField(blank=True, null=True)),
                ('option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_4', models.CharField(blank=True, max_length=100, null=True)),
                ('option_1_count', models.IntegerField(default=0)),
                ('option_2_count', models.IntegerField(default=0)),
                ('option_3_count', models.IntegerField(default=0)),
                ('option_4_count', models.IntegerField(default=0)),
                ('answered_user', models.ManyToManyField(blank=True, null=True, related_name='answered_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensei_app.questionpoll'),
        ),
    ]
