# Generated by Django 3.1 on 2020-11-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0014_auto_20201116_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='ニックネーム'),
        ),
    ]
