# Generated by Django 3.1 on 2020-11-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0015_auto_20201122_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True)),
                ('content', models.TextField()),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
