# Generated by Django 3.1 on 2020-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0016_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsconditions',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
