# Generated by Django 3.1 on 2020-11-30 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0020_auto_20201128_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
