# Generated by Django 3.1 on 2020-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0024_joblisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('question_num', models.IntegerField(blank=True, null=True)),
                ('question_head', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('answer', models.IntegerField(blank=True, choices=[(1, 'Choice1'), (2, 'Choice2'), (3, 'Choice3'), (4, 'Choice4'), (5, 'Choice5')], null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='address',
            field=models.TextField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='application_condition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='contact_person_private',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='deadline_supplement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='tel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='treatment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contract_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='listing_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='organization_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
