# Generated by Django 3.1 on 2020-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0025_auto_20201202_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examexp',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
