# Generated by Django 3.1 on 2020-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0026_auto_20201202_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='examexp',
            name='queston_num_small',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examexp',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
