# Generated by Django 3.1 on 2020-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0029_auto_20201204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='examexp',
            name='answer_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='answer_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='answer_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='answer_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='answer_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='answer_abc',
            field=models.BooleanField(default=False),
        ),
    ]
