# Generated by Django 3.1 on 2020-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0031_auto_20201205_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='examexp',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Difficult')], null=True),
        ),
    ]
