# Generated by Django 3.1 on 2020-12-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0032_examexp_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_slug', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examexp',
            name='after_exp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examexp',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='sensei_app.ExamTags'),
        ),
    ]
