# Generated by Django 3.1 on 2020-12-06 04:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0033_auto_20201206_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examexp',
            options={'ordering': ['-year', 'section', 'question_num', 'question_num_small']},
        ),
        migrations.AlterField(
            model_name='examexp',
            name='after_exp',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
