# Generated by Django 3.1 on 2020-12-21 11:59

from django.db import migrations, models
import sensei_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0036_auto_20201221_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='MinnaNoMaterial', validators=[sensei_app.validators.validate_pdf_or_MSO]),
        ),
    ]
