# Generated by Django 3.1 on 2020-12-22 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0037_auto_20201221_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-upload_at']},
        ),
        migrations.AddField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
