# Generated by Django 3.1 on 2020-12-22 12:19

from django.db import migrations, models
import sensei_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0039_auto_20201222_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='MinnaNoMaterial', validators=[sensei_app.validators.validate_pdf_or_MSO, sensei_app.validators.validate_file_size]),
        ),
    ]
