# Generated by Django 3.1 on 2020-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0043_blog_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
