# Generated by Django 3.1 on 2021-01-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0046_auto_20201228_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingStudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='application_condition',
            new_name='class_scale',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='email',
            new_name='contact_person_email',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='tel',
            new_name='contract_duration_month',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='deadline_supplement',
            new_name='dayoff',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='job_desc',
            new_name='message_to_applicants',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='notes',
            new_name='perk',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='treatment',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='job_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='contact_person_private',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='workplace',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='contract_duration_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_starting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='kimarishidai_end',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location_category',
            field=models.IntegerField(choices=[(1, 'Japan'), (2, 'Not Japan')], null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location_country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location_other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='organization_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='organization_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='posted_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='requirement_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='requirement_novice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='selection_process',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='working_hour',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category_posts', to='sensei_app.blogcategory'),
        ),
        migrations.AlterField(
            model_name='jltct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_notes', to='sensei_app.jltctcategory'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contact_person',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contract_type',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Difficult')], null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='listing_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='student_type',
            field=models.ManyToManyField(null=True, related_name='student_type_jobs', to='sensei_app.JobListingStudentType'),
        ),
    ]
