# Generated by Django 3.1 on 2021-01-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0047_auto_20210118_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
