# Generated by Django 3.1 on 2021-02-06 07:46

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_app', '0048_material_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examexp',
            name='explanation',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
